### ISSUE TITLE
Open Notify /iss-pass.json removed

### ISSUE THREAD

**Issue by ddey117** [learn-co-curriculum/dsc-http-request-response-lab#1]
Hello,
I was unable to interpret the results of my request when I went to review them on the open notify API. I am attaching a screenshot of the response I got. 

<img width="1311" alt="Screen Shot 2021-05-25 at 6 35 43 PM" src="https://user-images.githubusercontent.com/57695782/119581400-16c2d000-bd88-11eb-869b-947c273a7432.png">

**Comment by jilliankim** [comment]
Curriculum is updated to have a level up item
