### ISSUE TITLE
Overhead Pass Predictions for the International Space Station API no longer available on Open Notify

### ISSUE THREAD

**Issue by uijallen** [learn-co-curriculum/dsc-http-request-response-lab#5]
## Link to Canvas

https://learning.flatironschool.com/courses/5315/assignments/176478?module_item_id=388592

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [X ] Other (explain below)

## Describe the Issue

The Lab for HTTP Request/Cycle still references the API Overhead Pass Predictions for the International Space Station but according to the http://open-notify.org website, that API has been removed.

### Source

```
## Level Up (Optional) - Investigating other API endpoints

### Next pass of International space station for a given location

Let's repeat the exercise for another endpoint `iss-pass.json`. This endpoint is used to query the next pass of the space station on a given location.
```

### Concern

The Open Notify website states that the Next Pass api is no longer available.  When I am attempting to run through the level up it is returning a 404 error that it cannot be found.

http://open-notify.org/Open-Notify-API/ISS-Pass-Times/

## What OS Are You Using?

- [X ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by bpurdy-ds** [comment]
I spent some time looking for this data set, and I could not find it either. Since this is from a "Level Up" and we're in the process of simplifying our curriculum, I'll just remove this part.
Closed with commit. https://github.com/learn-co-curriculum/dsc-http-request-response-lab/issues/5#issue-1283862096
