### ISSUE TITLE
iss-pass api has been removed

### ISSUE THREAD

**Issue by cschneck7** [learn-co-curriculum/dsc-http-request-response-lab#6]
## Link to Canvas

https://learning.flatironschool.com/courses/5329/assignments/187442?module_item_id=417471

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [X ] Other (explain below)

### Source

```
Level Up (Optional) - Investigating other API endpoints
Next pass of International space station for a given location
Let's repeat the exercise for another endpoint iss-pass.json. This endpoint is used to query the next pass of the space station on a given location.
```

### Concern

The iss-pass api has been removed

http://open-notify.org/Open-Notify-API/ISS-Pass-Times/

## What OS Are You Using?

- [ ] OS X
- [X ] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by jessepisel** [comment]
This has been removed with commit 5f5b5f2a80fef96d213e3efbd6c53c6661e332de. I am closing this issue at this time.
