### ISSUE TITLE
Lab solution doesn't result the same result even with the same code

### ISSUE THREAD

**Issue by Tommyphung1** [learn-co-curriculum/dsc-http-request-response-lab#7]
## Link to Canvas

https://learning.flatironschool.com/courses/5874/assignments/217968?module_item_id=507955

## Issue Subtype

- [ ] Master branch code
- [x ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

## Describe the Issue
Thought I had the solution to the last problem but it still gave me an error so I looked at the solution. 
The solution looked almost the same so I copied it to see if I miss something but gave a similar error. 
### Source

```
# Set up the parameters we want to pass to the API.
# This is the latitude and longitude of New York City.
parameters = {"lat": 40.71, "lon": -74}

# Make a get request with the parameters.
response = requests.get("http://api.open-notify.org/iss-pass.json", params=parameters)
print(response.status_code)

# Print the content of the response (the data the server returned)
print(dict(response.headers))
print(response.text)
200
{'Server': 'nginx/1.10.3', 'Date': 'Thu, 31 Mar 2022 18:54:40 GMT', 'Content-Type': 'application/json', 'Content-Length': '519', 'Connection': 'keep-alive', 'Via': '1.1 vegur'}
{
  "message": "success", 
  "request": {
    "altitude": 100, 
    "datetime": 1648752200, 
    "latitude": 40.71, 
    "longitude": -74.0, 
    "passes": 5
  }, 
  "response": [
    {
      "duration": 647, 
      "risetime": 1648755267
    }, 
    {
      "duration": 580, 
      "risetime": 1648761143
    }, 
    {
      "duration": 570, 
      "risetime": 1648767017
    }, 
    {
      "duration": 639, 
      "risetime": 1648772833
    }, 
    {
      "duration": 627, 
      "risetime": 1648778642
    }
  ]
}
```

### Concern
 The solution isn't the same and looks like the error message is different from before. 
It may just need to be updated but unsure

## What OS Are You Using?

- [ ] OS X
- [] Windows
- [ ] WSL
- [ ] Linux
- [x ] IllumiDesk

## Any Additional Context?

The error resulted in 404 which the wiki says its not available rather than not found.

**Comment by jessepisel** [comment]
This portion of the lesson has been removed in commit 5f5b5f2a80fef96d213e3efbd6c53c6661e332de as the ISS pass API has been removed (see #5).

I am closing this issue at this time.
